# Workflow to do CI on the repository using a fixed version of Zenoh
name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-testing-latest
      
    steps:
      - run: sudo chown -R rosbuild:rosbuild "$HOME" .
        
      # Install additional dependencies
      - name: Install dependencies
        run: sudo apt install ros-foxy-test-osrf-testing-tools-cpp

      # Checkout the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          path: ws/src/rmw_zenoh

      # Check out the Zenoh source code and switch to the rust branch
      - name: Checkout Zenoh
        uses: actions/checkout@v2
        with:
          repository: eclipse-zenoh/zenoh
          ref: 21b346a20ed054d4b5ef025afefe33f4df2a2235
          path: zenoh

      # Set up Rust nightly
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1.0.1
        with:
          profile: minimal
          toolchain: nightly
          default: true
    
      # Compile Zenoh
      - name: Compile Zenoh
        run: |
          cd $GITHUB_WORKSPACE/zenoh
          cargo build --release --package zenoh-ffi
    
      # Copy the FFI files into the zenoh_ament package
      - name: Copy Zenoh FFI
        run: |
          mkdir $GITHUB_WORKSPACE/ws/src/rmw_zenoh/zenoh_ament/lib
          cp $GITHUB_WORKSPACE/zenoh/target/release/libzenoh_ffi.so $GITHUB_WORKSPACE/ws/src/rmw_zenoh/zenoh_ament/lib/
          cp $GITHUB_WORKSPACE/zenoh/zenoh-ffi/include/* $GITHUB_WORKSPACE/ws/src/rmw_zenoh/zenoh_ament/include/
      
      # Compile rmw_zenoh_cpp
      - name: Compile rmw_zenoh
        run: |
          . /opt/ros/foxy/setup.sh
          cd $GITHUB_WORKSPACE/ws
          colcon build
          
      # Test rmw_zenoh_cpp
      - name: Test rmw_zenoh_cpp
        run: |
          colcon test
          colcon test-result
