name: style
on:
  pull_request:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: ['iron', 'jazzy', 'rolling']
    container:
      image: ros:${{ matrix.distro }}-ros-base
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: uncrustify
      run: /ros_entrypoint.sh ament_uncrustify rmw_zenoh_cpp/
    - name: cpplint
      # Ignore logging.hpp since the fmt::sprintf gets incorrectly flagged by ament_cpplint
      # as a runtime/printf error.
      run: /ros_entrypoint.sh ament_cpplint rmw_zenoh_cpp/ --exclude rmw_zenoh_cpp/src/detail/logging.hpp
